spring:
  application:
    name: Green Ride

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: changeme
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # dev only
    open-in-view: false
    properties:
      hibernate.format_sql: true

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true

# App configuration
app:
  # JWT (για να μην σκάει το JwtService αν το έχεις ενεργό)
  jwt:
    secret: "CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_32CHARS_MINIMUM"
    issuer: "greenride"
    audience: "greenride-web"
    ttl-minutes: 60

  # External integrations
  noc:
    base-url: "http://localhost:8081"

  sms:
    base-url: "http://localhost:8081"