spring:
  application:
    name: Green Ride

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: changeme
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true

app:
  jwt:
    secret: "CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_32CHARS_MINIMUM"
    issuer: "greenride"
    audience: "greenride-web"
    ttl-minutes: 60

  noc:
    base-url: "http://localhost:8081"

  sms:
    base-url: "http://localhost:8081"

  weather:
    base-url: "https://api.open-meteo.com"

  maps:
    base-url: "https://api.openrouteservice.org"
    api-key: ${ORS_API_KEY:eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjVhMTg3NzdjNzA0MjQwZWJhYzYxNDUzYTMyNTNhMWM3IiwiaCI6Im11cm11cjY0In0=}

    spring:
      datasource:
        url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
        username: sa
        password: changeme
        driver-class-name: org.h2.Driver